env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
    - go get github.com/markbates/pkger/cmd/pkger
builds:
  - id: cli
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
    hooks:
      pre: pkger -include /assets -o ./cmd/
    dir: cmd
    main: .
  - id : gui
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
    hooks:
      pre: pkger -include /assets -o ./gui/
    dir: gui
    main: .

archives:
  - format: binary
    name_template: "hsk00-{{ .Os }}-{{ .Arch }}-cli"
    builds:
      - cli
  - format: binary
    name_template: "hsk00-{{ .Os }}-{{ .Arch }}-gui"
    builds:
      - gui

release:
  extra_files:

changelog:
  sort: asc
  filters:
    exclude:
      - "^[🔨⏪✅📝🔀 🚧].*"
