env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
    - go get github.com/markbates/pkger/cmd/pkger
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
    hooks:
      pre: pkger -include /assets
    dir: cmd
    main: .

archives:
  - format: binary
    name_template: "hsk00-{{ .Os }}-{{ .Arch }}"

release:
  extra_files:

changelog:
  sort: asc
  filters:
    exclude:
      - "^[🔨⏪✅📝🔀 🚧].*"
