on: 
  push: 
    branches:
      - main
  pull_request:

name: Test

jobs:

  test:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-20.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install Ubuntu Dependencies
      run: sudo apt clean && sudo apt update && sudo apt install build-essential libgtk-3-dev libwebkit2gtk-4.0-dev
      if: ${{ matrix.os == 'ubuntu-20.04' }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Vars
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Install Project Dep
      run: |
        go mod download
        go get github.com/markbates/pkger/cmd/pkger
    - name: Pkger
      run: |
        pkger -include /assets -o ./cmd
        pkger -include /assets
      env:
        GO111MODULE: on
    - name: Build CLI
      run: go build -o hsk00-cli ./cmd/*
      if: ${{ matrix.os != 'windows-latest' }}
    - name: Build Windows CLI
      run: cd cmd && go build -o ..\hsk00-cli.exe
      if: ${{ matrix.os == 'windows-latest' }}
      continue-on-error: true
    - name: Install Wails
      run: go get -u github.com/wailsapp/wails/cmd/wails
    - name: Setup Account
      run: mkdir -p ~/.wails && echo '{"email":"dev.drprasad@aim.com","name":"REDDY PRASAD"}' > ~/.wails/wails.json
    - name: Build GUI
      run: wails build -p -ldflags "-X main.CurrentVersionStr=${{ steps.vars.outputs.tag }}"
    - name: Make DMG
      run: npx create-dmg ./build/hsk00.app ./build
      continue-on-error: true
      if: ${{ matrix.os == 'macos-latest' }}
    - name: Linux tarball
      uses: master-atul/tar-action@v1.0.2
      id: linux-tarball
      if: ${{ matrix.os == 'ubuntu-20.04' }}
      continue-on-error: true
      with:
        command: c
        cwd: ./build
        files: hsk00
        outPath: ./build/hsk00.tar.gz
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}
        path: |
          ./build/hsk00.tar.gz
          ./build/hsk00.exe
          ./build/hsk00 0.1.0.dmg
